version: '3'
services:
  composer:
    image: composer:2.5.5
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app
  phpunit:
    image: php:8.1-cli
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit